from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


INPUT = Path(
    "research/m9_fill_hazard_markouts_2019-07-30.csv"
)

OUTPUT = Path(
    "research/m9_inventory_policy_2019-07-30.csv"
)


def main() -> None:

    df = pd.read_csv(INPUT)

    df = df.sort_values(
        ["symbol", "timestamp_ns"]
    ).copy()

    # Only the quote candidates that are generated by the
    # existing M9.4 process.
    #
    # We simulate inventory using completed fills.
    # Each fill contributes:
    # BUY  -> +filled_qty
    # SELL -> -filled_qty
    #
    # The policy does NOT alter the underlying market.
    # It is a diagnostic selection rule applied to the
    # already-generated candidates.

    results = []

    limits = [100, 200, 500, 1000]

    for inventory_limit in limits:

        for skew_strength in [0.25, 0.50, 1.00]:

            inventory = {
                symbol: 0.0
                for symbol in df["symbol"].unique()
            }

            selected = 0
            selected_fills = 0

            gross_filled_qty = 0.0
            signed_filled_qty = 0.0

            max_abs_inventory = 0.0

            for row in df.itertuples():

                symbol = row.symbol
                side = row.quote_side

                inv = inventory[symbol]

                # Inventory sign:
                # positive = long
                # negative = short
                #
                # Positive inventory suppresses BUYs and favors SELLs.
                # Negative inventory suppresses SELLs and favors BUYs.

                if side == "BUY":
                    inventory_pressure = inv
                else:
                    inventory_pressure = -inv

                # Normalize pressure by the inventory limit.
                normalized_pressure = (
                    inventory_pressure
                    / inventory_limit
                )

                # Simple deterministic score.
                #
                # score > 0 means the quote is aligned with
                # reducing current inventory.
                #
                # score < 0 means the quote increases exposure.

                score = -skew_strength * normalized_pressure

                # Hard risk limit.
                allowed = True

                if side == "BUY" and (
                    inv >= inventory_limit
                ):
                    allowed = False

                if side == "SELL" and (
                    inv <= -inventory_limit
                ):
                    allowed = False

                # Additional soft inventory preference.
                #
                # At extreme pressure, reject the quote.
                if score < -1.0:
                    allowed = False

                if not allowed:
                    continue

                selected += 1

                if row.outcome != "FILL":
                    continue

                fill_qty = float(row.filled_qty)

                selected_fills += 1
                gross_filled_qty += fill_qty

                if side == "BUY":
                    inventory[symbol] += fill_qty
                    signed_filled_qty += fill_qty
                else:
                    inventory[symbol] -= fill_qty
                    signed_filled_qty -= fill_qty

                max_abs_inventory = max(
                    max_abs_inventory,
                    abs(inventory[symbol]),
                )

            results.append(
                {
                    "inventory_limit": inventory_limit,
                    "skew_strength": skew_strength,
                    "selected_candidates": selected,
                    "selected_fills": selected_fills,
                    "selection_rate": (
                        selected / len(df)
                    ),
                    "fill_rate_selected": (
                        selected_fills / selected
                        if selected
                        else np.nan
                    ),
                    "gross_filled_qty": gross_filled_qty,
                    "net_filled_qty": signed_filled_qty,
                    "max_abs_inventory": max_abs_inventory,
                }
            )

    result = pd.DataFrame(results)

    OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    result.to_csv(
        OUTPUT,
        index=False,
    )

    print(
        "M9.7 inventory-policy diagnostic"
    )

    print(
        result.to_string(index=False)
    )

    print(
        f"\nSaved: {OUTPUT}"
    )


if __name__ == "__main__":
    main()